apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80

# kubectl expose deploy ngnix-deploy --name=ngnix-service --port=80 --target-port=80 --type=LoadBalancer
# kubectl get svc -l app=nginx-app
# kubectl describe service my-service
