apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs

spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app        
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80        
                
           
