#echo -n 'admin' > ./username.txt
#$ echo -n 'password55' > ./password.txt
#$ cat username.txt
#$ cat username.txt
#$ kubectl create secret generic db-user-pass --from-file=./username.txt --from-file=./password.txt
#secret/db-user-pass created
# to decrypt
#
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: db-user-pass

